name: Fairy

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Random commits generator
        run: |
          # Set up git config
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          
          # Generate a random number of commits for the day (e.g., between 5 and 20)
          RANDOM_COMMITS=$((RANDOM % 16 + 5)) # Minimum 5 commits, maximum 20
          echo "Number of commits today: $RANDOM_COMMITS"

          # Commit multiple times at random intervals
          for ((i=1; i<=RANDOM_COMMITS; i++)); do
            # Generate a random interval between 1 and 60 minutes
            RANDOM_INTERVAL=$((RANDOM % 60 + 1))
            echo "Waiting for $RANDOM_INTERVAL minute(s) before commit $i..."
            sleep $((RANDOM_INTERVAL * 60))
            
            # Create a unique empty commit with a timestamp
            git commit --allow-empty -m "Automated commit #$i: $(date +'%Y-%m-%d %H:%M:%S')"
          done

          # Push all commits
          git push origin master
