name: Fairy

on:
  schedule:
    - cron: '1 * * * *' # every hour at the first minute
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runner's shell
      - name: Run commit script
        run: |
          # Set up git config
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          
          # Generate a random minute (between 1 and 59)
          RANDOM_MINUTE=$((RANDOM % 60))
          
          # Wait for the random minute (sleep in seconds)
          echo "Waiting for $RANDOM_MINUTE minute(s) before committing..."
          sleep $((RANDOM_MINUTE * 60))
          
          # Make an empty commit with the current timestamp
          git commit --allow-empty -m "Automated commit: `date +'%Y-%m-%d %H:%M:%S'`"
          
          # Push the changes
          git push origin master
